### ISSUE TITLE
enforce_csrf function is incompatible with Django 4

### ISSUE THREAD

**Issue by robrap** [openedx/edx-drf-extensions#373]
The function [enforce_csrf](https://github.com/openedx/edx-drf-extensions/blob/master/edx_rest_framework_extensions/auth/jwt/authentication.py#L188-L201) seems to be incompatible with Django 4.0.

It causes errors like the following:
```
DEBUG    edx_rest_framework_extensions.auth.jwt.authentication:authentication.py:108 Failed JWT Authentication,
Traceback (most recent call last):
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/edx_rest_framework_extensions/auth/jwt/authentication.py", line 99, in authenticate
    self.enforce_csrf(request)
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/edx_rest_framework_extensions/auth/jwt/authentication.py", line 195, in enforce_csrf
    check = CSRFCheck()  # pylint: disable=no-value-for-parameter
TypeError: __init__() missing 1 required positional argument: 'get_response'
ERROR    django.request:log.py:241 Internal Server Error: /api/v1/enterprise-customer/66e4ae11-fa2e-4c4c-a21c-b37917655199/content-metadata/08b00577-ca80-47dc-8c95-6aacb2b454f6/
Traceback (most recent call last):
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/edx_rest_framework_extensions/auth/jwt/authentication.py", line 99, in authenticate
    self.enforce_csrf(request)
  File "/edx/app/enterprise_catalog/enterprise_catalog/.tox/py38-django40/lib/python3.8/site-packages/edx_rest_framework_extensions/auth/jwt/authentication.py", line 195, in enforce_csrf
    check = CSRFCheck()  # pylint: disable=no-value-for-parameter
TypeError: __init__() missing 1 required positional argument: 'get_response'
```

**Comment by robrap** [comment]
This may fix: https://github.com/openedx/edx-drf-extensions/pull/362
